version: "3.8"

services:
  db:
    image: timescale/timescaledb-ha:pg17
    container_name: movie-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=imdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:Z
    command: ["postgres", "-c", "maintenance_work_mem=1GB", "-c", "max_parallel_maintenance_workers=4"]

  agent:
    build: .   # Finds Dockerfile in root
    container_name: movie-rec-agent
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app:Z   # Shares entire movieRec directory
    depends_on:
      - db
    runtime: nvidia

volumes:
  postgres_data: